### ISSUE TITLE
Envío de mail para los formularios

### ISSUE THREAD

**Issue by iturrima** [iturrima/smab#1]
Resolver el sistema de envío de mails para utilizar en los formularios de contacto.

**Comment by iturrima** [comment]
Respecto a la info del servidor: Soporta Phyton pero no se puede acceder por ssh.

**Comment by foxcarlos** [comment]
Voy a crear un servicio en mi sitio web para el envio de emails, vamos a probarlo si funciona entonces discutimos donde se haria el backend te parece?

**Comment by iturrima** [comment]
Perfecto.
Matías Iturri

**Comment by foxcarlos** [comment]
[**BACKEND**] termine el server por ahora esta el correo de prueba hasta que se decida colocar el correo real

**Comment by foxcarlos** [comment]
[**FRONTEND**] Terminado el servicio en Angular para el envio de email, lo tengo en otra rama a la espera que vos subas los ultimos cambios asi aactualizo mi rama master y hago el merge

**Comment by foxcarlos** [comment]
Se mergeo mi cambio a la rama Master de Mati
